# _config.yml

title: Shaw Talebi
#logo: /assets/img/headshot_circle.png
description: "Innovating with Excellence in [Industry Name]. Shaw Talebi is a leader in delivering cutting-edge solutions and unparalleled customer service."

# Enable or disable downloads section on your site
Show_downloads: true

# Jekyll theme setting
theme: jekyll-theme-minimalist

# Navigation links
navbar:
  - title: "Home"
    url: "/"
  - title: "About Us"
    url: "/about"
  - title: "Services"
    url: "/services"
  - title: "Contact Us"
    url: "/contact"
  - title: "Careers"
    url: "/careers"
  - title: "Privacy Policy"
    url: "/privacy-policy"

# Social Media Links (Optional)
social_links:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/company/your-company"
  - name: "Twitter"
    url: "https://twitter.com/your-company"
  - name: "Facebook"
    url: "https://www.facebook.com/your-company"

# Footer Settings
footer:
  text: "© 2025 Shaw Talebi. All rights reserved."

# Show author information in blog (if blog exists)
author_info: true

# Disqus comments (if you plan to have a blog and want to enable comments)
comments:
  disqus_shortname: "your-disqus-shortname" # Replace with your Disqus shortname (if using Disqus)

# SEO Settings (for better visibility in search engines)
seo:
  title: "Shaw Talebi | Innovative Solutions"
  description: "Shaw Talebi provides high-quality services and innovative solutions to businesses worldwide."
  url: "https://www.shawtalebi.com"
  twitter_card: "summary_large_image"
  twitter_site: "@ShawTalebi"

# Markdown extensions for content (if needed)
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics (Optional)
google_analytics: "UA-XXXXXXX-X"  # Replace with your Google Analytics Tracking ID

# Theme settings
jekyll-theme-minimalist:
  # If you have a custom header image or background image
  header_image: "/assets/img/your-custom-header.jpg"
  
  # Other theme-specific settings
  header_text_color: "#FFFFFF"  # Example to adjust the text color on header images

# Language & Localization
locale: en
