title: DBS Innovation Enterprise
logo: /assets/img/DBS_logo.jpg
description: "Innovating with Excellence in Business Solutions. DBS Innovation Enterprise is a leader in delivering cutting-edge foldable stall solutions and unparalleled customer service."

# Enable or disable downloads section on your site
show_downloads: true

# Jekyll theme setting
theme: jekyll-theme-minimal

# Navigation links
navbar:
  - title: "Home"
    url: "/"
  - title: "About Us"
    url: "/about"
  - title: "Our Products"
    url: "/products"
  - title: "Why Choose Us"
    url: "/why-choose-us"
  - title: "Contact Us"
    url: "/contact"
  - title: "Careers"
    url: "/careers"
  - title: "Privacy Policy"
    url: "/privacy-policy"

# Social Media Links
social_links:
  - name: "Facebook"
    url: "https://www.facebook.com/dbsinnovation"
  - name: "Instagram"
    url: "https://www.instagram.com/dbsinnovation"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/company/dbsinnovation"

# Footer Settings
footer:
  text: "© 2025 DBS Innovation Enterprise. All rights reserved."

# SEO Settings
seo:
  title: "DBS Innovation Enterprise | Foldable Stall Solutions"
  description: "DBS Innovation Enterprise provides high-quality, innovative, and portable business solutions across Malaysia."
  url: "https://www.dbsinnovation.com"
  twitter_card: "summary_large_image"
  twitter_site: "@dbsinnovation"

# Markdown extensions for content (if needed)
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics (Optional)
google_analytics: "UA-XXXXXXX-X"  # Replace with your Google Analytics Tracking ID

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Language & Localization
locale: en
